In [1]:
import torch

In [15]:
x = torch.arange(12)
print(x)
print(x[0])
print(type(x[0]))
print(type(x))
print(x[0].dtype)
print(x.dtype)
print(x.shape)
print(x.numel())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor(0)
<class 'torch.Tensor'>
<class 'torch.Tensor'>
torch.int64
torch.int64
torch.Size([12])
12


In [16]:
X = x.reshape(3, 4)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [13]:
y = torch.tensor([0.1,0.2,0.3])
print(y)
print(y.dtype)

tensor([0.1000, 0.2000, 0.3000])
torch.float32


In [17]:
print(torch.zeros(2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [20]:
print(torch.ones(2,3,4))
print(torch.ones(2,3,4).dtype)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.float32


In [22]:
#Each of its elements is randomly sampled from a standard Gaussian (normal) distribution with a mean of 0 and a standard deviation of 1.
print(torch.randn(3,4))

tensor([[ 1.1249,  0.7133,  0.7921, -0.7354],
        [-1.3470, -0.5395, -0.2937,  0.2744],
        [ 0.1525,  0.5048, -0.8443,  0.5925]])


In [23]:
print(torch.tensor([[2,1,4,3],[3,4,5,8],[8,9,5,3]]))

tensor([[2, 1, 4, 3],
        [3, 4, 5, 8],
        [8, 9, 5, 3]])


# Operations

## elementwise operations

In [24]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**y)

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])


In [25]:
print(torch.exp(x))

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


In [30]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(X)
print(Y)
print(torch.cat((X, Y), dim = 0))
print(torch.cat((X, Y), dim = 1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [31]:
print(X == Y)

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


In [32]:
print(X.sum())

tensor(66.)


## Broadcasting Mechanism

In [33]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print(a)
print(b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


In [34]:
print(a + b)

tensor([[0, 1],
        [1, 2],
        [2, 3]])


## indexing and slicing

In [35]:
print(X)
print(X[-1])
print(X[1:3])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [36]:
X[1, 2] = 9
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])


In [37]:
X[0:2, :] = 12
print(X)

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


## Saving Memory

In [38]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [41]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140409995621792
id(Z): 140409995621792


In [42]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z = X + Y
print('id(Z):', id(Z))

id(Z): 140409995408000
id(Z): 140409995410960


In [43]:
before = id(X)
X += Y
id(X) == before

True

In [44]:
before = id(X)
X = X + Y
id(X) == before

False

In [45]:
before = id(X)
X[:] = X + Y
id(X) == before

True

## The Conversion between Numpy and Tensor

In [59]:
print(X)
A = X.numpy()
print(A)
B = torch.tensor(A)
print(type(A))
print(type(B))
print(id(A))
print(id(B))

tensor([[54., 51., 60., 57.],
        [51., 54., 57., 60.],
        [44., 45., 46., 47.]])
[[54. 51. 60. 57.]
 [51. 54. 57. 60.]
 [44. 45. 46. 47.]]
<class 'numpy.ndarray'>
<class 'torch.Tensor'>
140409995162928
140409995600672


In [60]:
np.add(A, 1, out = A)
print(A)
print(B)

[[55. 52. 61. 58.]
 [52. 55. 58. 61.]
 [45. 46. 47. 48.]]
tensor([[54., 51., 60., 57.],
        [51., 54., 57., 60.],
        [44., 45., 46., 47.]])


In [57]:
print(A)
print(B)
B = B + torch.tensor([1,1,1,1])
print(B)
print(A)

[[54. 51. 60. 57.]
 [51. 54. 57. 60.]
 [44. 45. 46. 47.]]
tensor([[54., 51., 60., 57.],
        [51., 54., 57., 60.],
        [44., 45., 46., 47.]])
tensor([[55., 52., 61., 58.],
        [52., 55., 58., 61.],
        [45., 46., 47., 48.]])
[[54. 51. 60. 57.]
 [51. 54. 57. 60.]
 [44. 45. 46. 47.]]


In [62]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
a.add_(1)
print(a)
print(b)
print(id(a))
print(id(b))
np.add(b, 1, out = b)
print("b:",b)
print("a:",a)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
140409994965232
140409994968000
b: [3. 3. 3. 3. 3.]
a: tensor([3., 3., 3., 3., 3.])


In [55]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)
print(id(a))
print(id(b))

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
140409995121168
140409995406544


In [58]:
print(a)
print(a)
b = b + torch.tensor([1,1,1,1,1])
print(b)
print(a)

[2. 2. 2. 2. 2.]
[2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
[2. 2. 2. 2. 2.]


# Using Pandas to genarate csv file



In [66]:
import os
os.makedirs(os.path.join('..','data'),exist_ok = True)
data_file = os.path.join('..', 'data', 'housing_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # Column names
    f.write('NA,Pave,127500\n')  # Each row represents a data example
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [67]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


## Handling Missing Data
* two methods
> * Imputation
> * Deletion

### Imputation

In [68]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [69]:
inputs = pd.get_dummies(inputs, dummy_na = True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [71]:
print(inputs.values)
print(type(inputs.values))

[[3. 1. 0.]
 [2. 0. 1.]
 [4. 0. 1.]
 [3. 0. 1.]]
<class 'numpy.ndarray'>


In [73]:
print(outputs.values)
print(type(outputs.values))

[127500 106000 178100 140000]
<class 'numpy.ndarray'>


## Conversion to Tensor Format

In [75]:
import torch
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
print(X)
print(y)
print(y.dtype)

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)
tensor([127500, 106000, 178100, 140000])
torch.int64


In [79]:
demo = torch.tensor([1,2,3,4,5])
print(demo)
demo_one = np.array([1,2,3,5])
print(demo_one)
demo_one_out = torch.tensor(demo_one)
demo_one_out

tensor([1, 2, 3, 4, 5])
[1 2 3 5]


tensor([1, 2, 3, 5])